version: "3.5"
services:
  app:
    container_name: app
    build: .
    tty: true
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: sh ./build.sh
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    volumes:
      - $PWD/infrastructure/postgres/init:/docker-entrypoint-initdb.d