version: "3.5"
services:
  @@.ImportPath@@:
    container_name: @@.ImportPath@@
    build: .
    tty: true
    restart: always
    volumes:
      - .:/app
    depends_on:
      - @@.ImportPath@@db
    ports:
      - 8080:8080
    command: sh ./build.sh
  @@.ImportPath@@db:
    image: postgres:10-alpine
    container_name: @@.ImportPath@@db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    volumes:
      - $PWD/infrastructure/postgres/init:/docker-entrypoint-initdb.d